## Numpy

http://numpy.org

High-performance vector, matrix and higher-dimensional data structures for Python. A core data type provider for the scientific python stack.

For a comprehensive tutorial, refer to this material:

http://wiki.scipy.org/Tentative_NumPy_Tutorial


In [40]:
import numpy as np

Q1. What is an array in numpy? An compact representation of like-kind data. 

In [41]:
array_data = [1, 2, 3, 4]

In [42]:
array = np.array(array_data)
array

array([1, 2, 3, 4])

In [43]:
array.dtype

dtype('int32')

#### Numpy has a large number of methods that translate to matlab/R/IDL commands. (ufuncs)

In [44]:
array.sum()

10

In [45]:
array.min(), array.mean(), array.max()

(1, 2.5, 4)

In [46]:
np.median(array)

2.5

Q2. How do you index data quickly with numpy? **Fancy indexing**.

In [53]:
matrix = np.random.randint(0, 100, (5, 5))
matrix

array([[32, 49, 51, 11, 97],
       [18, 18, 43, 18, 68],
       [63, 41, 81, 96, 77],
       [24,  6,  7, 87, 49],
       [84, 39, 61, 98, 82]])

In [54]:
matrix.shape

(5, 5)

In [55]:
matrix > 50

array([[False, False,  True, False,  True],
       [False, False, False, False,  True],
       [ True, False,  True,  True,  True],
       [False, False, False,  True, False],
       [ True, False,  True,  True,  True]], dtype=bool)

- - - 
Fancy indexing can be used to slice into data in complex ways (boolean expressions) and form views of data.
- - - 

In [56]:
matrix[matrix>50]

array([51, 97, 68, 63, 81, 96, 77, 87, 84, 61, 98, 82])

Q2. What if the coordinates are important? **nonzero**

In [61]:
rows, cols = np.nonzero(matrix>50)

In [62]:
matrix[rows, cols]

array([51, 97, 68, 63, 81, 96, 77, 87, 84, 61, 98, 82])

- - - 
Broadcasting is a way to perform operations on data quickly avoiding iteration.
- - - 

In [76]:
matrix = np.ones((3,3))
matrix

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [77]:
5.0 * matrix

array([[ 5.,  5.,  5.],
       [ 5.,  5.,  5.],
       [ 5.,  5.,  5.]])

Q3. Multiply a matrix by a row of data, without iterating through the matrix rows.

In [85]:
np.r_[[1, 2, 3]] * matrix

array([[ 1.,  2.,  3.],
       [ 1.,  2.,  3.],
       [ 1.,  2.,  3.]])

Q4. Multiply a matrix by a column of data, without iterating through the matrix columns.

In [84]:
np.c_[[1, 2, 3]] * matrix

array([[ 1.,  1.,  1.],
       [ 2.,  2.,  2.],
       [ 3.,  3.,  3.]])

- - -
Numpy allows operations to happen at a lower level without itteration, a process called vectorization. 
- - - 